###% Developping tools library
###% 

basicHM <- function(x, ...){
	aheatmap(x, hclustfun="average"
			, Rowv=NA, Colv=TRUE, ...
	)
}

if( !exists('.NMFpackageDir', .GlobalEnv) )
	assign('.NMFpackageDir', getwd(), env=.GlobalEnv)

#TODO: outdir does not work when plots are generated by the test functions by checkPlot
runTestNMF <- function(outdir='.', file=NULL, reload=TRUE, ...){
	
	# script directory
	sdir <- .NMFpackageDir
	sdir <- normalizePath(sdir)
	
	# load scripts
	if( reload )
		source(file.path(sdir,'package.R'), chdir=TRUE)
	
	# load RUnit modified library
	library(RUnitX)
	
	# setup the output directory
	dir.create(outdir, showWarnings=FALSE)
	wd.bkp <- getwd()
	on.exit(setwd(wd.bkp), add=TRUE)
	setwd(outdir)
	
	if( !is.null(file) ){
		# run the test file
		testfile <- file.path(sdir,'../tests', file)
		if( !file.exists(testfile) ){
			# try to add prefix and suffix of test files
			
			testfile <- file.path(dirname(testfile), paste('runit', basename(testfile), 'r', sep='.'))			
			if( !file.exists(testfile) )
				stop("Could not resolve test file: '", file, "' does not exist")
		}
		
		testResult <- runTestFile(testfile,
				rngKind = RNGkind()[1],
				#rngNormalKind = "Kinderman-Ramage"
				...)
	}else{
		# define the test suite
		testsuite.nmf <- defineTestSuite("nmf",
				dirs = file.path(sdir,'../tests'),
				testFileRegexp = "^runit.+\\.r",
				testFuncRegexp = "^test.+",
				rngKind = RNGkind()[1],
		#rngKind = "Marsaglia-Multicarry",
		#rngNormalKind = "Kinderman-Ramage"
		)
		
		# run the test suite
		testResult <- runTestSuite(testsuite.nmf)
	}
	
	# export the test results	
	printTextProtocol(testResult, fileName='test.txt')
	printHTMLProtocol(testResult, fileName='index.html')
}

###% Source function to enable VComments
sourceV <- function(...){
	sourceSmart(..., debug=FALSE)	
}
sourceD <- function(...){
	sourceSmart(..., debug=TRUE)	
}

sourceSmart <- function(file, comWarnings=FALSE, debug=FALSE, ...){
	
	# define processing functions
	sourceDebug <- VComments$compile	
	sourceLog <- function(lines, ...){
		lines = LComments$compile(lines, ...)
		sourceComments(lines, ...)
	}	
	
	if( require(R.utils) ){
		oldHooks <- getHook("sourceTo/onPreprocess")
		setHook("sourceTo/onPreprocess", if( debug ) sourceLog else sourceDebug, action="replace")
		if( comWarnings ) sourceTo(file, ...)
		else suppressWarnings(sourceTo(file, local=FALSE, ...)) 
		setHook("sourceTo/onPreprocess", oldHooks, action="replace")
	}else{
		warning('Unable to load R.utils')
		source(file, ...)
	}
	
}
